---
title: "Stroke Prediction Model Report"
author: "Simão Tavares | João Cordeiro | Tomás Matias | Rodrigo Curto"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: flatly
    df_print: paged
fontsize: 11pt
---

```{r Libraries and Data Cleaning, echo=FALSE, include=FALSE}
############################
# Load necessary libraries #
############################
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(gt)
library(scales)
library(patchwork)

##############################
# Download and data cleaning #
##############################
dados_unsort <- read_csv("healthcare-dataset-stroke-data.csv", na = c("","NA","N/A", "Unknown"))
dados_unsort$id = as.numeric(dados_unsort$id)
dados = dados_unsort[order(dados_unsort$id), ]

#Data structure

dados$bmi = as.numeric(dados$bmi)
dados$age=as.integer(dados$age)
unique(dados$gender)
dados$gender = factor(dados$gender, levels = c("Female", "Male", "Other"))
unique(dados$hypertension)
dados$hypertension = factor(dados$hypertension, levels = c(0, 1), labels = c("No", "Yes"))
unique(dados$heart_disease)
dados$heart_disease = factor(dados$heart_disease, levels = c(0, 1), labels = c("No", "Yes"))
unique(dados$ever_married)
dados$ever_married = factor(dados$ever_married, levels = c("No", "Yes"))
unique(dados$work_type)
dados$work_type = factor(dados$work_type, levels = c("Private", "Self-employed", "Govt_job", "children", "Never_worked"))
unique(dados$Residence_type)
dados$Residence_type = factor(dados$Residence_type, levels = c("Urban", "Rural"))
unique(dados$smoking_status)
dados$smoking_status = factor(dados$smoking_status, levels = c("never smoked", "formerly smoked", "smokes"))# Unknown means that the information is unavailable for this patient
unique(dados$stroke)
dados$stroke = factor(dados$stroke, levels = c(0, 1), labels = c("No", "Yes"))


```

# Exploratory Data Analysis

```{r fig.cap="Figure 1: Stroke status across all the qualitative variables", echo=FALSE, fig.align='center', results='asis', out.width="100%"}
#Stroke~Gender

p1 = ggplot(dados, aes(x=gender, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Gender", y="Proportion") +
  theme_classic() +
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")


#Stroke~Hypertension

p2 = ggplot(dados, aes(x=hypertension, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Hypertension", y="Proportion") +
  theme_classic()+
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")


#Stroke~heart_disease
p3 = ggplot(dados, aes(x=heart_disease, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Heart Disease", y="Proportion") +
  theme_classic()+
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")

#Stroke~ever married
p4 = ggplot(dados, aes(x=ever_married, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="The patient ever married", y="Proportion") +
  theme_classic()+
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")

#Stroke~work type
p5 = ggplot(dados, aes(x=work_type, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Work Type", y="Proportion") +
  theme_classic()+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),  # <-- rótulos inclinados
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")+
  scale_x_discrete(labels = c("Private", "Self-employed", "Government\nJob", "Children", "Never\nWorked"))

#Stroke~Residence type
p6 = ggplot(dados, aes(x=Residence_type, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Residence Type", y="Proportion") +
  theme_classic()+
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")


combine = (p1 + p2 + p3)/(p4 + p5 + p6) + plot_annotation(tag_levels = 'A') & theme(legend.position = 'bottom')
combine

```





