---
title: "Stroke Prediction Model Report"
author: "Simão Tavares | João Cordeiro | Tomás Matias | Rodrigo Curto"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: flatly
    df_print: paged
fontsize: 11pt
---

```{r Libraries and Data Cleaning, echo=FALSE, include=FALSE}
############################
# Load necessary libraries #
############################
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(gt)
library(scales)
library(patchwork)
library(broom)
library(flextable)
library(QuantPsyc)
library(gtsummary)
library(lmtest)
library(car)
library(psych)
library(GGally)
library(corrplot)
library(Hmisc)
library(rms)
##############################
# Download and data cleaning #
##############################
dados_unsort <- read_csv("healthcare-dataset-stroke-data.csv", na = c("","NA","N/A", "Unknown"))
dados_unsort$id = as.numeric(dados_unsort$id)
dados_unsort=dados_unsort[dados_unsort$gender != "Other",] #remove 1 observação. Como só uma pessoa tinha este género, não havia uma amostra representativa de pessoas desta categoria com e sem AVCs, logo, posteriormente, os modelos poderiam ser afetados
dados = dados_unsort[order(dados_unsort$id), ]

#Data structure

dados$age=as.integer(dados$age)
unique(dados$gender)
dados$gender = factor(ifelse(dados$gender=="Female","Feminino","Masculino"),
                             levels = c("Feminino","Masculino"))
unique(dados$hypertension)
dados$hypertension = factor(dados$hypertension, levels = c(0, 1), labels = c("Não", "Sim"))
unique(dados$heart_disease)
dados$heart_disease = factor(dados$heart_disease, levels = c(0, 1), labels = c("Não", "Sim"))
unique(dados$ever_married)
dados$ever_married = factor(ifelse(dados$ever_married=="No","Não","Sim"),
                            levels = c("Não", "Sim"))
unique(dados$Residence_type)
dados$Residence_type = factor(ifelse(dados$Residence_type=="Urban","Urbano","Rural"),
                              levels = c("Urbano", "Rural"))
unique(dados$stroke)
dados$stroke = factor(dados$stroke, levels = c(0, 1), labels = c("Não", "Sim"))
dados$work_type = factor(ifelse(dados$work_type==c("Self-employed"),
                         "Trabalha por conta própria","Trabalha por conta de outrém"),
                         levels=c("Trabalha por conta de outrém","Trabalha por conta própria"))

dados = dados[,c(2:12)]

```


#Imputação de dados
```{r Imputação, echo=FALSE}
imputar = aregImpute(formula = ~stroke + age + hypertension + heart_disease + ever_married + Residence_type + avg_glucose_level + bmi + smoking_status + gender + work_type, data = dados, n.impute = 5, nk = 3)
#n.imput é o número de imputações (5 recomendado por Harrell)
# nk = número de "nós" (knots) para as curvas (splines). 
# O padrão é 3, o que permite captar relações não lineares (curvas)

plot(imputar)

```


## Modelos com imputação


```{r Modelos com imput, echo=FALSE}
modelo_imput_log = fit.mult.impute(formula = stroke ~ age + hypertension + heart_disease + ever_married + Residence_type + avg_glucose_level + bmi + smoking_status, fitter = lrm, xtrans = imputar, data = dados)

print(modelo_imput_log)



modelo_imput_lin = fit.mult.impute(formula = stroke ~ age + hypertension + heart_disease + ever_married + Residence_type + avg_glucose_level + bmi + smoking_status, fitter = lm, xtrans = imputar, data = dados)

print(modelo_imput_lin)


```




