---
title: "Stroke Prediction Model Report"
author: "Simão Tavares | João Cordeiro | Tomás Matias | Rodrigo Curto"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    theme: flatly
    df_print: paged
fontsize: 11pt
---

```{r Libraries and Data Cleaning, echo=FALSE, include=FALSE}
############################
# Load necessary libraries #
############################
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(gt)
library(scales)
library(patchwork)
library(broom)
library(flextable)
##############################
# Download and data cleaning #
##############################
dados_unsort <- read_csv("healthcare-dataset-stroke-data.csv", na = c("","NA","N/A", "Unknown"))
dados_unsort$id = as.numeric(dados_unsort$id)
dados = dados_unsort[order(dados_unsort$id), ]

#Data structure

dados$bmi = as.numeric(dados$bmi)
dados$age=as.integer(dados$age)
unique(dados$gender)
dados$gender = factor(dados$gender, levels = c("Female", "Male", "Other"))
unique(dados$hypertension)
dados$hypertension = factor(dados$hypertension, levels = c(0, 1), labels = c("No", "Yes"))
unique(dados$heart_disease)
dados$heart_disease = factor(dados$heart_disease, levels = c(0, 1), labels = c("No", "Yes"))
unique(dados$ever_married)
dados$ever_married = factor(dados$ever_married, levels = c("No", "Yes"))
unique(dados$work_type)
dados$work_type = factor(dados$work_type, levels = c("Private", "Self-employed", "Govt_job", "Children", "Never_worked"))
unique(dados$Residence_type)
dados$Residence_type = factor(dados$Residence_type, levels = c("Urban", "Rural"))
unique(dados$smoking_status)
dados$smoking_status = factor(dados$smoking_status, levels = c("never smoked", "formerly smoked", "smokes"))# Unknown means that the information is unavailable for this patient
unique(dados$stroke)
dados$stroke = factor(dados$stroke, levels = c(0, 1), labels = c("No", "Yes"))


```

# Exploratory Data Analysis

## Qualitative Variables

```{r Qualitative Variables, fig.cap="Figure 1: Stroke status across all the qualitative variables", echo=FALSE, fig.align='center', results='asis', out.width="70%"}


#Stroke~Gender

p1 = ggplot(dados, aes(x=gender, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Gender", y="Proportion") +
  theme_classic() +
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")
#Stroke~Hypertension

p2 = ggplot(dados, aes(x=hypertension, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Hypertension", y="Proportion") +
  theme_classic()+
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")
#Stroke~heart_disease

p3 = ggplot(dados, aes(x=heart_disease, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Heart Disease", y="Proportion") +
  theme_classic()+
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")

#Stroke~ever married

p4 = ggplot(dados, aes(x=ever_married, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="The patient ever married", y="Proportion") +
  theme_classic()+
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")

#Stroke~work type

p5 = ggplot(dados, aes(x=work_type, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Work Type", y="Proportion") +
  theme_classic()+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),  # <-- rótulos inclinados
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")+
  scale_x_discrete(labels = c("Private", "Self-employed", "Government\nJob", "Children", "Never\nWorked"))

#Stroke~Residence type

p6 = ggplot(dados, aes(x=Residence_type, fill=stroke)) +
  geom_bar(position="fill") +
  labs(x="Residence Type", y="Proportion") +
  theme_classic()+
  theme(
    axis.title = element_text(size = 10),      # título dos eixos
    axis.text = element_text(size = 8),        # números nos eixos
    legend.title = element_text(size = 9),     # título da legenda
    legend.text = element_text(size = 7),      # texto da legenda
    plot.title = element_text(size = 12)       # título do gráfico
  )+
  scale_y_continuous(labels = scales::percent)+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")



combine = (p1 + p2 + p3)/(p4 + p5 + p6) + plot_annotation(tag_levels = 'A') & theme(legend.position = 'bottom')
combine

```

## Absolute Frequencies Tables




```{r Tables, fig.cap = "Table 1: Absolute frequencies of the qualitative variables", echo=FALSE, fig.align='center', results='asis', out.width="70%"}

# Summary table Stroke~Gender

tbl_val=table(dados$stroke,dados$gender)
df_tbl=as.data.frame(tbl_val)
colnames(df_tbl)=c("Stroke","Gender","Freq")
new_table=reshape(df_tbl,idvar = "Stroke",
                  timevar = "Gender",
                  v.names = "Freq",
                  direction = "wide")
new_table=new_table[order(new_table$Stroke),]
colnames(new_table)=c("Stroke","Female","Male","Other")
new_table$Total=rowSums(new_table[,c("Female","Male","Other")])
somas_col=colSums(new_table[,c("Female","Male","Other","Total")])
linha_total=data.frame(Stroke="Total",Female=somas_col["Female"],
                       Male=somas_col["Male"],Other=somas_col["Other"],
                       Total=somas_col["Total"])
new_table=rbind(new_table,linha_total)
final_table=flextable(new_table)
final_table=merge_v(final_table,j=1) #junta as colunas iguais
final_table=add_header_row(final_table, values=c("","Gender",""),
                           colwidths=c(1,3,1))
final_table=align(final_table, align = "center", part = "all")
final_table=bold(final_table,part="header")
final_table=bold(final_table,j="Stroke",part="body")
final_table=vline(final_table,j=c(1,2,3,4)) #linhas verticais
final_table=hline(final_table,i=c(1,2)) #linhas horizontais
final_table=vline_left(final_table)
final_table=vline_right(final_table)
final_table




# Summary table Stroke~Hypertension

tbl_val=table(dados$stroke,dados$hypertension)
df_tbl=as.data.frame(tbl_val)
colnames(df_tbl)=c("Stroke","Hypertension","Freq")
new_table=reshape(df_tbl,idvar = "Stroke",
                  timevar = "Hypertension",
                  v.names = "Freq",
                  direction = "wide")
new_table=new_table[order(new_table$Stroke),]
colnames(new_table)=c("Stroke","No","Yes")
new_table$Total=rowSums(new_table[,c("No","Yes")])
somas_col=colSums(new_table[,c("No","Yes","Total")])
linha_total=data.frame(Stroke="Total",No=somas_col["No"],
                       Yes=somas_col["Yes"],Total=somas_col["Total"])
new_table=rbind(new_table,linha_total)
final_table=flextable(new_table)
final_table=merge_v(final_table,j=1) #junta as colunas iguais
final_table=add_header_row(final_table, values=c("","Hypertension",""),
                           colwidths=c(1,2,1))
final_table = align(final_table, align = "center", part = "all")
final_table=bold(final_table,part="header")
final_table=bold(final_table,j="Stroke",part="body")
final_table=vline(final_table,j=c(1,2,3,4)) #linhas verticais
final_table=hline(final_table,i=c(1,2)) #linhas horizontais
final_table=vline_left(final_table)
final_table=vline_right(final_table)
final_table



# Summary table Stroke~Heart disease

tbl_val=table(dados$stroke,dados$heart_disease)
df_tbl=as.data.frame(tbl_val)
colnames(df_tbl)=c("Stroke","Heart Disease","Freq")
new_table=reshape(df_tbl,idvar = "Stroke",
                  timevar = "Heart Disease",
                  v.names = "Freq",
                  direction = "wide")
new_table=new_table[order(new_table$Stroke),]
colnames(new_table)=c("Stroke","No","Yes")
new_table$Total=rowSums(new_table[,c("No","Yes")])
somas_col=colSums(new_table[,c("No","Yes","Total")])
linha_total=data.frame(Stroke="Total",No=somas_col["No"],
                       Yes=somas_col["Yes"],Total=somas_col["Total"])
new_table=rbind(new_table,linha_total)
final_table=flextable(new_table)
final_table=merge_v(final_table,j=1) #junta as colunas iguais
final_table=add_header_row(final_table, values=c("","Heart Disease",""),
                           colwidths=c(1,2,1))
final_table = align(final_table, align = "center", part = "all")
final_table=bold(final_table,part="header")
final_table=bold(final_table,j="Stroke",part="body")
final_table=vline(final_table,j=c(1,2,3,4)) #linhas verticais
final_table=hline(final_table,i=c(1,2)) #linhas horizontais
final_table=vline_left(final_table)
final_table=vline_right(final_table)
final_table




# Summary table Stroke~Marriage Status

tbl_val=table(dados$stroke,dados$ever_married)
df_tbl=as.data.frame(tbl_val)
colnames(df_tbl)=c("Stroke","Ever Married?","Freq")
new_table=reshape(df_tbl,idvar = "Stroke",
                  timevar = "Ever Married?",
                  v.names = "Freq",
                  direction = "wide")
new_table=new_table[order(new_table$Stroke),]
colnames(new_table)=c("Stroke","No","Yes")
new_table$Total=rowSums(new_table[,c("No","Yes")])
somas_col=colSums(new_table[,c("No","Yes","Total")])
linha_total=data.frame(Stroke="Total",No=somas_col["No"],
                       Yes=somas_col["Yes"],Total=somas_col["Total"])
new_table=rbind(new_table,linha_total)
final_table=flextable(new_table)
final_table=merge_v(final_table,j=1) #junta as colunas iguais
final_table=add_header_row(final_table, values=c("","Ever Married?",""),
                           colwidths=c(1,2,1))
final_table = align(final_table, align = "center", part = "all")
final_table=bold(final_table,part="header")
final_table=bold(final_table,j="Stroke",part="body")
final_table=vline(final_table,j=c(1,2,3,4)) #linhas verticais
final_table=hline(final_table,i=c(1,2)) #linhas horizontais
final_table=vline_left(final_table)
final_table=vline_right(final_table)
final_table




# Summary table Stroke~Work Type

tbl_val=table(dados$stroke,dados$work_type)
df_tbl=as.data.frame(tbl_val)
colnames(df_tbl)=c("Stroke","Work Type","Freq")
new_table=reshape(df_tbl,idvar = "Stroke",
                  timevar = "Work Type",
                  v.names = "Freq",
                  direction = "wide")
colnames(new_table)=c("Stroke","Private","Self-employed","Government Job",
                      "Children","Never Worked")
new_table$Total=rowSums(new_table[,c("Private","Self-employed","Government Job",
                                     "Children","Never Worked")])
somas_col=colSums(new_table[,c("Private","Self-employed","Government Job",
                               "Children","Never Worked","Total")])
linha_total=data.frame(Stroke="Total","Private"=somas_col["Private"],
                       "Self-employed"=somas_col["Self-employed"],
                       "Government Job"=somas_col["Government Job"],
                       "Children"=somas_col["Children"],
                       "Never Worked"=somas_col["Never Worked"],
                       Total=somas_col["Total"],check.names=F)
new_table=rbind(new_table,linha_total)
final_table=flextable(new_table)
final_table=merge_v(final_table,j=1) #junta as colunas iguais
final_table=add_header_row(final_table, values=c("","Work type",""),
                           colwidths=c(1,5,1))
final_table = align(final_table, align = "center", part = "all")
final_table=bold(final_table,part="header")
final_table=bold(final_table,j="Stroke",part="body")
final_table=vline(final_table,j=c(1,2,3,4,5,6)) #linhas verticais
final_table=hline(final_table,i=c(1,2)) #linhas horizontais
final_table=vline_left(final_table)
final_table=vline_right(final_table)
final_table

# Summary table Stroke~Residence Type

tbl_val=table(dados$stroke,dados$Residence_type)
df_tbl=as.data.frame(tbl_val)
colnames(df_tbl)=c("Stroke","Residence Type","Freq")
new_table=reshape(df_tbl,idvar = "Stroke",
                  timevar = "Residence Type",
                  v.names = "Freq",
                  direction = "wide")
colnames(new_table)=c("Stroke","Urban","Rural")
new_table$Total=rowSums(new_table[,c("Urban","Rural")])
somas_col=colSums(new_table[,c("Urban","Rural","Total")])
linha_total=data.frame(Stroke="Total","Urban"=somas_col["Urban"],
                       "Rural"=somas_col["Rural"],
                       Total=somas_col["Total"])
new_table=rbind(new_table,linha_total)
final_table=flextable(new_table)
final_table=merge_v(final_table,j=1) #junta as colunas iguais
final_table=add_header_row(final_table, values=c("","Residence type",""),
                           colwidths=c(1,2,1))
final_table = align(final_table, align = "center", part = "all")
final_table=bold(final_table,part="header")
final_table=bold(final_table,j="Stroke",part="body")
final_table=vline(final_table,j=c(1,2,3)) #linhas verticais
final_table=hline(final_table,i=c(1,2)) #linhas horizontais
final_table=vline_left(final_table)
final_table=vline_right(final_table)
final_table

```


## Quantitative Variables


```{r Quantitative Variables, fig.cap="Figure 2: Stroke status across all the quantitative variables", echo=FALSE, fig.align='center', results='asis', out.width="70%"}

a1=ggplot(dados, aes(x = avg_glucose_level, fill = stroke))+
  geom_histogram(position = "identity", bins = nclass.Sturges(dados$avg_glucose_level))+
  labs(title="Stroke status and Average Glucose Level", x="Average Glucose Level", y="Count") +
  theme_classic()+
  scale_fill_manual(values=c("red3", "forestgreen"), name="Stroke Status")

a2=ggplot(subset(dados,stroke=="Yes"),aes(x=avg_glucose_level))+
  geom_histogram(fill="forestgreen",bins=nclass.Sturges(dados$avg_glucose_level))+
  labs(title="Stroke's distribution across Average Glucose Levels intervals", x="Average Glucose Level", y="Count")+
  theme_classic()

(a1+a2)+plot_layout(nrow=2) #isto permite-nos ver se as distribuições são minimamente semelhantes


```


## Stroke vs Age and Sex


```{r fig.cap="Figure 3: Relationship between Stroke Status and Age and Sex", echo=FALSE, fig.align='center', results='asis', out.width="100%", warning=FALSE}

#Este chunk está a dar um warning, para o ver colocar TRUE

#Stroke~Age and Sex (gender=Other was excluded as there was only one answer of this type, so it is not logical to create a boxplot)

ggplot(subset(dados,gender!="Other"),aes(x=stroke,y=age))+
  geom_boxplot()+
  labs(title="Age Distribution for Stroke and Non-Stroke\nPatients per Gender",
       y="Age",x="Did you have a stroke?")+
  facet_wrap(~gender)+
  coord_flip()+
  theme_classic()+
  theme(plot.title=element_text(hjust=0.5,size=15,face="bold"),
        legend.text=element_text(size=10),
        legend.title=element_text(size=11,face="bold"),
        panel.border=element_rect(color="black",fill=NA,size=1),
        panel.spacing=unit(1,"lines"))

```


# Linear Model
A partir daqui está o nosso modelo de regressão linear. Este envolve as variáveis quantitativas do nosso dataset

```{r Linear Model, fig.cap="Figure 1: Stroke status across all the qualitative variables", echo=FALSE, fig.align='center', results='asis', out.width="100%"}

########################################
#Linear and Logistic Regression Models #
########################################
correlation_matrix <- dados %>%
  select(age, bmi, avg_glucose_level) %>%
  cor(use = "complete.obs")

correlation_matrix
#age vs bmi
modelo_BMI_age <- lm(bmi ~ age, data = dados)
summary(modelo_BMI_age)

ggplot(dados, aes(x = age, y = bmi)) +
  geom_point(alpha=0.4) +
  geom_smooth(method="lm", se=TRUE) +
  labs(x = "Age (years)", y = "BMI",
       title = "Relationship between BMI and Age") +
  theme_classic()
#glucose vs age
modelo_glucose_age <- lm(avg_glucose_level ~ age, data = dados)
summary(modelo_glucose_age)

ggplot(dados, aes(x = age, y = avg_glucose_level)) +
  geom_point(alpha=0.4) +
  geom_smooth(method="lm", se=TRUE) +
  labs(x = "Age (years)", y = "Average Glucose Level",
       title = "Relationship between Blood Glucose and Age") +
  theme_classic()

#glucose vs bmi
modelo_bmi_glucose <- lm(bmi ~ avg_glucose_level, data = dados)
summary(modelo_bmi_glucose)

ggplot(dados, aes(x = avg_glucose_level, y = bmi)) +
  geom_point(alpha=0.4) +
  geom_smooth(method="lm", se=TRUE) +
  labs(x = "Average Glucose Level", y = "BMI",
       title = "Relationship between Blood Glucose and Age") +
  theme_classic()


#Esses gráficos não são para prever nada, são para verificar se a regressão linear é estatisticamente válida
par(mfrow = c(2,2))
plot(modelo_BMI_age)
plot(modelo_glucose_age)
plot(modelo_bmi_glucose)
par(mfrow = c(1,1))

#IC dos coeficientes
confint(modelo_BMI_age)
confint(modelo_glucose_age)
confint(modelo_bmi_glucose)

#tabelas bonitas das informações

tidy(modelo_BMI_age, conf.int = TRUE) %>% 
  gt() %>% 
  tab_header(title = "Regression BMI ~ Age")

tidy(modelo_glucose_age, conf.int = TRUE) %>% 
  gt() %>% 
  tab_header(title = "Regression Glucose ~ Age")

tidy(modelo_bmi_glucose, conf.int = TRUE) %>% 
  gt() %>% 
  tab_header(title = "Regression BMI ~ Glucose")

```


